### ISSUE TITLE
Google sign-in fails

### ISSUE THREAD

**Issue by anirvan-majumdar** [nikhil-31/HackerNewsFirebaseApp#2]
Error message (toast) pops up saying: _Google sign-in failed, please try again_

**Comment by nikhil-31** [comment]
Hi,

If built using the debug build the Google sign in will fail as the sha1 key
for your system is not added. Please build using release or the apk
provided and make sure internet is connected. The release keystore and
password are all in the apps build.gradle.

**Comment by nikhil-31** [comment]
To run the code with the release build. In the app build.gradle file
config {
      keyAlias 'key0'
      keyPassword 'hackme789'
      storeFile file(' /** Change path to the keystore present in the root of the app in your machine **/')
      storePassword 'hacker12345'
    }
Debug builds will not work as the SHA-1 key unique to your system is not present in the firebase console.

I have downloaded and tested it with the current apk file and google sign in is working

**Comment by nikhil-31** [comment]
Added a check to see if the device is connected to a network, if not connected will show an appropriate error message. Tested with all my google accounts and found working with APK in root folder.
