### ISSUE TITLE
Article list view has janking on first time login

### ISSUE THREAD

**Issue by anirvan-majumdar** [nikhil-31/HackerNewsFirebaseApp#3]
When a user logs-in for the first time, there's quite a bit of [jank](https://developer.android.com/training/testing/performance.html#measure) while scrolling the list view. This might be due to the fact the article data is getting fetched simultaneously. Try and optimise the recycler view refresh while the data is being fetched.

**Comment by nikhil-31** [comment]
Hi,

Jank is due to high number of requests being made. Problem will be solved
if I use a job priority queue and update in background. Time constraint
prevented me but I will do it tonight.

**Comment by nikhil-31** [comment]
Hi,

This has been fixed with the latest release the realm db insert now happens async. So UI should be jank free.
Will Close this issue now.
